### ISSUE TITLE
AzureVMCluster throwing: AttributeError: 'AzureVMScheduler' object has no attribute 'protocol'

### ISSUE THREAD

**Issue by manuelreyesgomez** [dask/dask-cloudprovider#247] opened 2021-01-28 03:38 UTC
On a new python 3.7 conda environment

$ pip install dask-cloudprovider[azure] 
$ az login
$ python
```python
Python code:

from dask_cloudprovider.azure import AzureVMCluster

resource_group = "NGC-AML-Quick-Launch"
vnet="NGC-AML-Quick-Launch-vnet"
security_group="NGC-AML-Quick-Launch-nsg"
initial_node_count = 2
vm_name = "Standard_NC6s_v3"
location = "South Central US"
base_dockerfile = "rapidsai/rapidsai:cuda11.0-runtime-ubuntu18.04-py3.7"

cluster = AzureVMCluster(
    resource_group=resource_group,
    location = location,
    vnet=vnet,
    security_group=security_group,
    n_workers=initial_node_count,
    vm_size=vm_name,
    docker_image=base_dockerfile,
    docker_args="--privileged",
    worker_class="dask_cuda.CUDAWorker")
```
Output:

```python-traceback
Creating scheduler instance
Assigned public IP
Network interface ready
Creating VM
Created VM dask-919fbb35-scheduler
Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
  File "C:\Users\mreyesgomez\Anaconda3\envs\AzureVMCluster_3_7__01_27_2021_no_change\lib\site-packages\dask_cloudprovider\azure\azurevm.py", line 496, in __init__
    super().__init__(**kwargs)
  File "C:\Users\mreyesgomez\Anaconda3\envs\AzureVMCluster_3_7__01_27_2021_no_change\lib\site-packages\dask_cloudprovider\generic\vmcluster.py", line 284, in __init__
    super().__init__(**kwargs, security=self.security)
  File "C:\Users\mreyesgomez\Anaconda3\envs\AzureVMCluster_3_7__01_27_2021_no_change\lib\site-packages\distributed\deploy\spec.py", line 281, in __init__
    self.sync(self._start)
  File "C:\Users\mreyesgomez\Anaconda3\envs\AzureVMCluster_3_7__01_27_2021_no_change\lib\site-packages\distributed\deploy\cluster.py", line 189, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "C:\Users\mreyesgomez\Anaconda3\envs\AzureVMCluster_3_7__01_27_2021_no_change\lib\site-packages\distributed\utils.py", line 340, in sync
    raise exc.with_traceback(tb)
  File "C:\Users\mreyesgomez\Anaconda3\envs\AzureVMCluster_3_7__01_27_2021_no_change\lib\site-packages\distributed\utils.py", line 324, in f
    result[0] = yield future
  File "C:\Users\mreyesgomez\Anaconda3\envs\AzureVMCluster_3_7__01_27_2021_no_change\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Users\mreyesgomez\Anaconda3\envs\AzureVMCluster_3_7__01_27_2021_no_change\lib\site-packages\dask_cloudprovider\generic\vmcluster.py", line 324, in _start
    await super()._start()
  File "C:\Users\mreyesgomez\Anaconda3\envs\AzureVMCluster_3_7__01_27_2021_no_change\lib\site-packages\distributed\deploy\spec.py", line 309, in _start
    self.scheduler = await self.scheduler
  File "C:\Users\mreyesgomez\Anaconda3\envs\AzureVMCluster_3_7__01_27_2021_no_change\lib\site-packages\distributed\deploy\spec.py", line 71, in _
    await self.start()
  File "C:\Users\mreyesgomez\Anaconda3\envs\AzureVMCluster_3_7__01_27_2021_no_change\lib\site-packages\dask_cloudprovider\generic\vmcluster.py", line 87, in start
    self.address = f"{self.protocol}://{ip}:8786"
AttributeError: 'AzureVMScheduler' object has no attribute 'protocol'
```

**Environment**:

- Dask version: (whatever comes with dask-cloudprovider[azure] )
- Python version: 3.7
- Operating System:
- Install method (conda, pip, source): pip

**Comment by anderl80** [comment] 2021-01-28 06:58
Same issue over here. Happy to help!

**Comment by anderl80** [comment] 2021-01-28 07:08
Tried to reproduce with fresh Python 3.8 env and ran into same issue again.

```bash
conda create -n dask python=3.8 ipykernel -y
conda activate dask
pip install dask-cloudprovider[azure]
python -m ipykernel install --user --name dask --display-name "Python 3.8 (dask)"
```

**Comment by jacobtomlinson** [comment] 2021-01-28 10:36
Whoops looks like I broke something when resolving a merge conflict during release. Opened a PR to fix, will push a new release today.

**Closed** 2021-01-28 10:41 UTC
Labels: bug
