### ISSUE TITLE
_cleanup_stale_resources doesn't perform tag checking and deregisters ALL ECS task definitions

### ISSUE THREAD

**Issue by AndrewHannigan** [dask/dask-cloudprovider#237] opened 2021-01-13 16:57 UTC
No tag checking when deregistering task definitions.  Causes `_cleanup_stale_resources` to deregister _every_ task definition returned by list_tag_definitions that wasn't created by dask cloudprovider, very dangerous and a major issue.

https://github.com/dask/dask-cloudprovider/blob/e93069bf3a5bb296bbb844c1d16709a9c25e3e62/dask_cloudprovider/aws/ecs.py#L1400-L1416

This effectively says deregister any task definition that either:
1. Doesn't have a "cluster" tag
OR
2. Does have a cluster tag, but it doesn't match up with an active cluster previously tagged as `createdBy: "dask-cloudprovider"`

This evaluates to all task definitions not created by dask cloudprovider.  

Only task definitions tagged as createdBy dask-cloudprovider should be eligible for deregistration by this cleanup process.

**Comment by jacobtomlinson** [comment] 2021-01-14 10:36
Duplicate of #94

**Closed by jacobtomlinson** 2021-01-14 10:36 UTC
