### ISSUE TITLE
Support Fargate Spot?

### ISSUE THREAD

**Issue by dirtyValera** [dask/dask-cloudprovider#311] opened 2021-09-24 10:46 UTC
I'm trying to figure out how to run worker tasks on Fargate Spot. Looks like it is done by specifying FARGATE_SPOT capacity provider for a cluster (which is done by default, since we set launchType=FARGATE) and using a custom capacity provider strategy. What is not clear to me is to how to specify that scheduler task should use FARGATE capacity provider and worker tasks should use FARGATE_SPOT. According to [this tutorial](https://ecsworkshop.com/capacity_providers/fargate/), strategies use notion of weights (e.g. half tasks on providerA, half on providerB), without the option to map tasks to providers. What other options are there?

**Comment by jacobtomlinson** [comment] 2021-09-24 14:23
This is a duplicate of #47

**Closed** 2021-09-24 14:24 UTC
